name: forge
description: 网络
version: 0.0.5
author: Tyrant
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^3.0.0
  dio: ^3.0.10
  rxdart: ^0.24.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^3.5.0
  
flutter:
